### ISSUE TITLE
start-health-check.sh: No such file or directory

### ISSUE THREAD

**Issue by televisi** [lux4rd0/sense-collector#11]
Hello,

Thanks for such a great script!
I tried to run it using the following docker-compose.yml

```
services:
  sense-1234:
    container_name: sense-1234
    environment:
      TZ: Australia/Sydney
      SENSE_COLLECTOR_HOST_HOSTNAME: ubuntu
      SENSE_COLLECTOR_INFLUXDB_PASSWORD: 1233123
      SENSE_COLLECTOR_INFLUXDB_URL: http://influxdb01.com:8086/write?db=sense
      SENSE_COLLECTOR_INFLUXDB_USERNAME: sensuser
      SENSE_COLLECTOR_TOKEN: xxx
      SENSE_COLLECTOR_MONITOR_ID: 1234
    image: lux4rd0/sense-collector:latest
version: '3.3'
```

For some reason, when I ran the docker, it keeps throwing this message:
```
sense-init: Starting Health Check
/sense-collector/sense-collector-init.sh: line 103: ./start-health-check.sh: No such file or directory
sense-init: Starting Health Check
/sense-collector/sense-collector-init.sh: line 103: ./start-health-check.sh: No such file or directory

```

Did I miss anything?

Thanks
